#pragma once


#define SHARK_WINDOW_WIDTH  500
#define SHARK_WINDOW_HEIGHT 500
#define SHARK_WINDOW_TITLE  "Raining Sharks"

#define SHARK_CAMERA_RECT_WIDTH 191
#define SHARK_CAMERA_RECT_HEIGHT 199


